apiVersion: v1
kind: Service
metadata:
  name: {{ include "aletheia-core.fullname" . }}
  labels:
    {{- include "aletheia-core.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort | default "http" }}
      protocol: TCP
      name: http
  selector:
    {{- include "aletheia-core.selectorLabels" . | nindent 4 }}
